# Generated by Django 5.0.1 on 2024-10-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
